### ISSUE TITLE
Probelm in publishing the message

### ISSUE THREAD

**Issue by fei123ilike** [nav74neet/rl4uav#1]
I created a package based on the Q-Learning.py script, installed all the dependencies, and could not visualize it in the gazebo. 

I checked the rostopic, they were
/ardrone/land
/ardrone/navdata
/ardrone/takeoff
/cmd_vel
/ground_truth/state
/rosout
/rosout_agg

Then I tried to print out the info of the topic using rostopic echo /ardrone/navdata, still nothing.

Also I checked the rostpic, they were
/control_script
/rosout

Can you help me?

**Comment by ycsh-w** [comment]
Hi! I successfully launch an environment in gazebo and then launch the Q-Learning.py. However, I observed that the drone jumped up for once and doing nothing since then. Have you figured out how to fix this? Thanks in advance!

**Comment by navuboy** [comment]
@fei123ilike I guess you must have missed on some of the dependencies/packages while settingup. DO check once again.

**Comment by fei123ilike** [comment]
Problem solved by installing gazobo_ros and tum_ardrone package.

**Comment by ChrisSun99** [comment]
May I ask how to start visualization of the training using tum_drone? Currently I'm following 3.2 in  https://wiki.ros.org/tum_ardrone and `rosrun uav_nav Q-learning.py` where uav_nav is a package that contains the Q-learning code. Any response is appreciated!
